export const MIN_SAFE_WATER_TEMPERATURE_FOR_TRAINED = 2;
export const MIN_SAFE_WATER_TEMPERATURE_FOR_UNTRAINED = 25;

export const MAX_SAFE_WATER_TEMPERATURE = 40;

export const WATER_EXPOSURE_DURATION_FORM_FIELD_DESCRIPTION_TRANSLATION_KEY =
  'calculateMentalLayersCleansedDuration';
